### ISSUE TITLE
UI popup on dashboard on battery devices

### ISSUE THREAD

**Issue by mcmikev** [pipiche38/Domoticz-Zigate-UI#1]
On the main dashboard of the UI, when pressing on the lower right part (Device Status , battery) then there comes a popup windows with the devices. I cannot close that window. Not with escape or button.
On the last page (in my situation page 3) there is a button on top CLOSE .

No option to close on page 1 or 2. Maybe that can be fixed.
PS: I view this on a microsoft surface pro 4, this device has a high resolution)

![F0FDFEC1-61A9-42DA-AE4D-6690389FEF2B](https://user-images.githubusercontent.com/10433087/59978572-0c1cc080-95de-11e9-9e63-b007d0f54a77.jpg)
![F3A6457B-BDD8-42A2-9A54-8705F3968A17](https://user-images.githubusercontent.com/10433087/59978574-10e17480-95de-11e9-907f-8dbe1609c21a.jpg)

**Comment by ben33880** [comment]
we decide to remove widget name and show battery level so only 5 rows will appear.
on Chrome, u must click in the popup and ESC.
