### ISSUE TITLE
Display Plugin Version and inform if there is an update

### ISSUE THREAD

**Issue by pipiche38** [pipiche38/Domoticz-Zigate-UI#12]
With REST API /plugin you get information on :

FirmwareUpdate: true or false
PluginUpdate: true or false
PluginBranch: beta or stable
PluginVersion: version of plugin
FirmwareVersion: version of Firmware
avaialble: plugin version available
available-firmMajor: version of Firmware available

Indeed the 
<img width="292" alt="Screenshot 2019-07-05 at 21 46 23" src="https://user-images.githubusercontent.com/8291674/60742769-ea70f100-9f6e-11e9-81ba-eb6c63c2105d.png">

**Comment by ben33880** [comment]
when we arrive on the home page, dashboard, can I open a modal presenting the updates? 

on the dashboard it can be interesting to view the plugin firmware plugin versions?

**Comment by ben33880** [comment]
Pushed
