### ISSUE TITLE
Restart Plugin doesn't work if UserName and Password are empty

### ISSUE THREAD

**Issue by pipiche38** [pipiche38/Domoticz-Zigate-UI#13]
A user is having a problem where the Restart Plugin doesn't work.

It looks like the following request is getting a 401 error code.

I suspect that is because username and password are not set by the user .

http://ip-address:port-num/json.htm?type=command&param=updatehardware&htype=94&idx=48&name=Zigate&username=&password=&address=ip-zigate-wifi&port=9999&serialport=/dev/ttyUSB-ZiGate&Mode1=USB&Mode2=255&Mode3=False&Mode4=False&Mode5=null&Mode6=0&extra=Zigate&enabled=true&datatimeout=0

**Comment by pipiche38** [comment]
It does work.
http://rasp.local:8080/json.htm?type=command&param=updatehardware&htype=94&idx=35&name=zigate&username=&password=&address=0.0.0.0&port=0&serialport=/dev/ttyUSBRPI3&Mode1=PI&Mode2=0&Mode3=False&Mode4=False&Mode5=False&Mode6=0&extra=Zigate&enabled=true&datatimeout=0

**Comment by pipiche38** [comment]
Looking after 401 . it is  Unauthorized Error .

**Comment by mcmikev** [comment]
Hi,

In domoticz I have webprotection setup with a username and password, but that is only to secure domoticz because I have published domoticz to internet and this prevents anyone being able to get into my domoitcz, and then i have about 6 users created and I am one of them with admin rights and all devices, I am logged in to domoticz with my credentials NOT the webprotection credentials. Then It does not work,

**Comment by pipiche38** [comment]
Access to XMLHttpRequest at 'http://192.168.xxxxx:8080/json.htm?type=command&param=updatehardware&htype=94&idx=48&name=Zigate&username=xxxx&password=yyyyy&address=192.168.x.x&port=9999&serialport=/dev/ttyUSB-ZiGate&Mode1=USB&Mode2=255&Mode3=False&Mode4=&Mode5=&Mode6=0&extra=Zigate&enabled=true&datatimeout=0' from origin 'http://192.168.150.123:9440' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.1a3a67b5399f2cf02592.js:1 [Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.


polyfills.1cb40309c5baa057bcbf.js:1 GET http://192.168.xxxxx:8080/json.htm?type=command&param=updatehardware&htype=94&idx=48&name=Zigate&username=xxxxx&password=yyyyy&address=192.168.x.x&port=9999&serialport=/dev/ttyUSB-ZiGate&Mode1=USB&Mode2=255&Mode3=False&Mode4=&Mode5=&Mode6=0&extra=Zigate&enabled=true&datatimeout=0 net::ERR_FAILED
