### ISSUE TITLE
Inconsistency between Number of End devices and what is listed

### ISSUE THREAD

**Issue by pipiche38** [pipiche38/Domoticz-Zigate-UI#15]
As shown in the screenshot, Dashboard reported 8 End Devices, while if clicking on we get only 5 End devices listed

<img width="516" alt="Screenshot 2019-09-01 at 12 06 15" src="https://user-images.githubusercontent.com/8291674/64074855-0e238f80-ccb1-11e9-8040-754bcb76be28.png">
<img width="1258" alt="Screenshot 2019-09-01 at 12 06 24" src="https://user-images.githubusercontent.com/8291674/64074856-0e238f80-ccb1-11e9-8a04-f0d48fa1a750.png">

**Comment by pipiche38** [comment]
Could be related to a different sorting/searching element.
IN this particular case, the End device not listed do not have a Battery value set !

**Comment by ben33880** [comment]
this.devicesOnBattery = devices.filter((device: any) => device.Battery !== '');
in dashboard.component.ts

**Comment by ben33880** [comment]
devices is result of zdevice api

**Comment by ben33880** [comment]
how can i know that device is battery one ?

**Comment by pipiche38** [comment]
Which API do you use ?

**Comment by pipiche38** [comment]
It looks not the same to compute the number of End Device, comparing to the list of End Devices

**Comment by pipiche38** [comment]
zDevice-Name you get a decoded Macapa
For End Device
MacCapa :
0 : "RFD"
1 : "Battery"

For Router
MacCapa :
0 : "FFD"
1 : "RxonIdle"
2 : "MainPower"

**Comment by ben33880** [comment]
i use zdevice

**Comment by pipiche38** [comment]
Thanks
