### ISSUE TITLE
When validating Group update , a refresh must be done

### ISSUE THREAD

**Issue by pipiche38** [pipiche38/Domoticz-Zigate-UI#24]
After the Group update validation, a refresh must be done

The main issue, is that if you do the refresh immediately after the call to the REST API for updating the group, the update might not be ready yet.

From a User standpoint I don't know what is acceptable

- A button to click to get it refresh
- A load of Dashboard page
- ...

**Comment by ben33880** [comment]
Can call api 1 second or every second until  plugin Say ok.

**Comment by pipiche38** [comment]
The plugin doesn't really have a state, where it can say it is ok.

Can we do something like that

(1) Click on Validate

    Wait 3 seconds (eventually with a Time counter or decounting )

Then you refresh
