### ISSUE TITLE
Energy Map histogram or Spider diagram - Sorting Channels

### ISSUE THREAD

**Issue by pipiche38** [pipiche38/Domoticz-Zigate-UI#7]
From one scan to an other the channels are not always in a sorted way
<img width="1338" alt="Screenshot 2019-06-29 at 13 26 09" src="https://user-images.githubusercontent.com/8291674/60383472-7b2c6600-9a71-11e9-8dd2-6baca1c5fc99.png">

**Comment by pipiche38** [comment]
I did a change on the Backend side. Let monitor if we still have that issue .

**Comment by pipiche38** [comment]
Seems that issue is still present. Can you sort on the Channel number ?

**Comment by ben33880** [comment]
ok

**Comment by pipiche38** [comment]
Merci
