### ISSUE TITLE
Makes menu available only if enabled

### ISSUE THREAD

**Issue by pipiche38** [pipiche38/Domoticz-Zigate-UI#86]
In the context of the zigpy integration, some commands/menu do not make sense , would it be possible to disable some of the menu or sub-menus if a particular flag from the /health API or anyother

Manly those 2 sub-menus
Network > Interference Level should be disabled in zigpy mode
Tools > Command > Zigate command (raw) should be disabled

**Comment by ben33880** [comment]
done
